module Rhopalic

  # Known contractions in English mapped to syllable counts.
  CONTRACTIONS = {
    "aren't" => 1,
    "can't" => 1,
    "couldn't" => 2,
    "didn't" => 2,
    "doesn't" => 2,
    "don't" => 1,
    "hadn't" => 2,
    "hasn't" => 2,
    "haven't" => 2,
    "he'd" => 1,
    "he'll" => 1,
    "he's" => 1,
    "i'd" => 1,
    "i'll" => 1,
    "i'm" => 1,
    "i've" => 1,
    "isn't" => 2,
    "it'll" => 2,
    "it's" => 1,
    "let's" => 1,
    "mightn't" => 2,
    "mustn't" => 2,
    "shan't" => 1,
    "she'd" => 1,
    "she'll" => 1,
    "she's" => 1,
    "shouldn't" => 2,
    "that's" => 1,
    "there'd" => 1,
    "there'll" => 1,
    "there's" => 1,
    "they'd" => 1,
    "they'll" => 1,
    "they're" => 1,
    "they've" => 1,
    "we'd" => 1,
    "we're" => 1,
    "we've" => 1,
    "weren't" => 2,
    "what'll" => 2,
    "what're" => 2,
    "what's" => 1,
    "what've" => 2,
    "where's" => 1,
    "who'd" => 1,
    "who'll" => 1,
    "who're" => 1,
    "who's" => 1,
    "who've" => 1,
    "won't" => 1,
    "wouldn't" => 2,
    "y'all" => 1,
    "you'd" => 1,
    "you'll" => 1,
    "you're" => 1,
    "you've" => 1,
  }

end